"""Mock SME personas for demo."""

PERSONAS = {
    "borrower_001": {
        "name": "Nguyen Van A",
        "scenario": "Strong traditional profile",
        "bank_data": {
            "monthly_income": 50_000_000,
            "dti": 0.25,
            "on_time_rate": 0.96,
            "annual_inc": 600_000_000,
            "loan_amnt": 80_000_000,
            "revol_util": 0.30,
            "open_acc": 5,
            "pub_rec": 0,
            "delinq_2yrs": 0,
            "inq_last_6mths": 1,
            "mort_acc": 1,
            "int_rate": 9.5,
        },
        "utility_data": {"on_time_rate": 0.98, "months_history": 36},
        "mobile_data": {"monthly_volume": 45_000_000, "consistency_score": 0.92},
        "profile": {
            "gender": "male",
            "age_group": "35-45",
            "region": "urban",
            "employment_type": "business_owner",
        },
        "expected_decision": "APPROVE",
    },
    "borrower_002": {
        "name": "Tran Thi B",
        "scenario": "Thin-file but strong alternative data",
        "bank_data": None,  # No bank account
        "utility_data": {"on_time_rate": 0.95, "months_history": 48},
        "mobile_data": {"monthly_volume": 30_000_000, "consistency_score": 0.89},
        "profile": {
            "gender": "female",
            "age_group": "25-35",
            "region": "rural",
            "employment_type": "self_employed",
        },
        "expected_decision": "APPROVE",
    },
    "borrower_003": {
        "name": "Le Van C",
        "scenario": "Borderline case",
        "bank_data": {
            "monthly_income": 20_000_000,
            "dti": 0.55,
            "on_time_rate": 0.72,
            "annual_inc": 240_000_000,
            "loan_amnt": 40_000_000,
            "revol_util": 0.65,
            "open_acc": 3,
            "pub_rec": 0,
            "delinq_2yrs": 1,
            "inq_last_6mths": 3,
            "mort_acc": 0,
            "int_rate": 15.0,
        },
        "utility_data": {"on_time_rate": 0.80, "months_history": 12},
        "mobile_data": {"monthly_volume": 10_000_000, "consistency_score": 0.65},
        "profile": {
            "gender": "male",
            "age_group": "25-35",
            "region": "suburban",
            "employment_type": "employee",
        },
        "expected_decision": "ESCALATE",
    },
    "borrower_004": {
        "name": "Pham Van D",
        "scenario": "High risk profile",
        "bank_data": {
            "monthly_income": 15_000_000,
            "dti": 0.78,
            "on_time_rate": 0.55,
            "annual_inc": 180_000_000,
            "loan_amnt": 50_000_000,
            "revol_util": 0.88,
            "open_acc": 2,
            "pub_rec": 2,
            "delinq_2yrs": 3,
            "inq_last_6mths": 5,
            "mort_acc": 0,
            "int_rate": 22.0,
        },
        "utility_data": {"on_time_rate": 0.60, "months_history": 6},
        "mobile_data": {"monthly_volume": 5_000_000, "consistency_score": 0.40},
        "profile": {
            "gender": "male",
            "age_group": "18-25",
            "region": "rural",
            "employment_type": "self_employed",
        },
        "expected_decision": "DENY",
    },
}
